import { GardeDef } from "src/app/utils/interfaces";

export const GardeTabData: { tabname: string; defs: GardeDef[] }[] = [
  {
    tabname: "Minigarde",
    defs: [
      {
        year: 2020,
        title: "Kindergarde",
        leaders: ["Laura Rieger", "Pauline Müller", "Amelie Grundler"],
        active: [],
        show: "-",
      },
      {
        year: 2019,
        title: "Mäusegarde",
        show: "-",
        leaders: ["Laura Rieger", "Pauline Müller", "Amelie Grundler"],
        active: [
          "Klara Abele",
          "Valentina Bach",
          "Hanna Beck",
          "Alessa Burkert",
          "Taina Burkert",
          "Anna Eiberger",
          "Linnea Emer",
          "Hanna Frosch",
          "Mia Fürst",
          "Kathrin Halt",
          "Lotta Higler",
          "Larissa Hillenbrand",
          "Laura HIlsenbeck",
          "Finja Hocky",
          "Fina Holl",
          "Lotta Hummel",
          "Heidi Lutz",
          "Luci Maierhöfer",
          "Levia Petzold",
          "Linea Petzold",
          "Leni Rechtenbacher",
          "Kim Rieger",
          "Luzi Spaag",
          "Leni Strauß",
          "Lotta Wieser",
          "Hannah Wünsch",
        ],
      },
      {
        year: 2018,
        title: "Mäusegarde",
        show: "-",
        leaders: ["Sina Feuchter", "Jessica Rathgeb"],
        active: [
          "Klara Abele",
          "Valentina Bach",
          "Hanna Beck",
          "Alessa Burkert",
          "Taina Burkert",
          "Anna Eiberger",
          "Linnea Emer",
          "Hanna Frosch",
          "Mia Fürst",
          "Kathrin Halt",
          "Lotta Higler",
          "Larissa Hillenbrand",
          "Laura Hilsenbeck",
          "Finja Hocky",
          "Fina Holl",
          "Lotta Hummel",
          "Heidi Lutz",
          "Luci Maierhöfer",
          "Levia Petzold",
          "Linea Petzold",
          "Leni Rechtenbacher",
          "Kim Rieger",
          "Luzi Spaag",
          "Leni Strauß",
          "Lotta Wieser",
          "Hannah Wünsch",
        ],
      },
      {
        year: 2017,
        title: "Mäusegarde",
        show: "-",
        leaders: ["Sina Feuchter", "Jessica Rathgeb"],
        active: [
          "Klara Abele",
          "Valentina Bach",
          "Maria Barenthin",
          "Hanna Beck",
          "Joy Berger",
          "Taina Burkert",
          "Polly Dorn",
          "Anna Eiberger",
          "Hanna Frosch",
          "Mia Fürst",
          "Lotta Higler",
          "Larissa Hillenbrand",
          "Anni Landkammer",
          "Heidi Lutz",
          "Leni Mack",
          "Lia Maierhöfer",
          "Levia Petzold",
          "Emma Frankenreiter",
          "Leni Rechtenbacher",
          "Emily Rief",
          "Kim Rieger",
          "Celina Schürlein",
          "Lia Wieser",
          "Lotta Wieser",
          "Hannah Wünsch",
        ],
      },
      {
        year: 2016,
        title: "Mäusegarde",
        show: "-",
        leaders: ["Sina Feuchter", "Jessica Rathgeb"],
        active: [
          "Maria Barenthin",
          "Joy Berger",
          "Taina Burkert",
          "Polly Dorn",
          "Emma Frankenreiter",
          "Lotta Higler",
          "Larissa Hillenbrand",
          "Anni Landkammer",
          "Lia Maierhöfer",
          "Leni Rechtenbacher",
          "Emily Rief",
          "Celina Schürlein",
          "Lia Wieser",
          "Anna Eiberger",
          "Leni Mack",
          "Hanna Becker",
        ],
      },
    ],
  },
  {
    tabname: "Kindergarde",
    defs: [
      {
        year: 2020,
        title: "Kindergarde",
        show: "Alles Außerirdisch",
        leaders: ["Sina Liesch", "Jana Tuscher", "Jasmina Brenner"],
        active: [],
      },
      {
        year: 2019,
        title: "Minigarde",
        show: "-",
        leaders: ["Sina Liesch", "Jana Tuscher", "Jasmina Brenner"],
        active: [
          "Maria Barenthin",
          "Svenja Betzler",
          "Catharina Christ",
          "Carolin Eiberger",
          "Emma Frankenreiter",
          "Shirley Frei",
          "Lea Fürst",
          "Tatjana Fürst",
          "Ida Gold",
          "Vanessa Halt",
          "Jule Hammele",
          "Miriam Helmle",
          "Sophia Higler",
          "Louisa Kaufmann",
          "Fiona Kurz",
          "Anni Landkammer",
          "Mia Mai",
          "Lisa Maierhöfer",
          "Leonie Mayer",
          "Emily Rief",
          "Hannah Rieger",
          "Celina Schürlein",
          "Leni Vatter",
          "Emma Weber",
          "Melina Ziegelbauer",
        ],
      },
      {
        year: 2018,
        title: "Minigarde",
        show: "-",
        leaders: ["Sina Liesch", "Jana Tuscher", "Jasmina Brenner"],
        active: [
          "Maria Barenthin",
          "Svenja Betzler",
          "Catharina Christ",
          "Carolin Eiberger",
          "Emma Frankenreiter",
          "Shirley Frei",
          "Lea Fürst",
          "Tatjana Fürst",
          "Ida Gold",
          "Vanessa Halt",
          "Jule Hammele",
          "Miriam Helmle",
          "Sophia Higler",
          "Louisa Kaufmann",
          "Fiona Kurz",
          "Anni Landkammer",
          "Mia Mai",
          "Lisa Maierhöfer",
          "Leonie Mayer",
          "Emily Rief",
          "Hannah Rieger",
          "Selina Schürlein",
          "Leni Vatter",
          "Emma Weber",
          "Melina Ziegelbauer",
        ],
      },
      {
        year: 2017,
        title: "Minigarde",
        show: "-",
        leaders: ["Sina Liesch", "Jana Tuscher", "Jasmina Brenner"],
        active: [
          "Svenja Betzler",
          "Cathrina Christ",
          "Rabia Daud",
          "Anika Dürrschmitt",
          "Carolin Eiberger",
          "Shirley Frei",
          "Lea Fürst",
          "Tatjana Fürst",
          "Ida Gold",
          "Heidi Haas",
          "Vanessa Halt",
          "Jule Hammele",
          "Miriam Helmle",
          "Sophia Hilger",
          "Felizia Holzinger",
          "Louisa Kaufmann",
          "Fiona Kurz",
          "Sophie Lüdtke",
          "Mia Mai",
          "Lisa Maierhöfer",
          "Leonie Mayer",
          "Hannah Rieger",
          "Leni Vatter",
          "Emma Weber",
          "Melina Ziegelbauer",
        ],
      },
      {
        year: 2016,
        title: "Minigarde",
        show: "-",
        leaders: ["Sina Liesch", "Jana Tuscher", "Jasmina Brenner"],
        active: [
          "Lara Berger",
          "Svenja Betzler",
          "Cathrina Christ",
          "Rabia Daud",
          "Anika Dürrschmitt",
          "Carolin Eiberger",
          "Shirley Frei",
          "Lea Fürst",
          "Tatjana Fürst",
          "Sarah Gerold",
          "Ida Gold",
          "Heidi Haas",
          "Vanessa Halt",
          "Jule Hammele",
          "Pia Hauber",
          "Miriam Helmle",
          "Sophia Higler",
          "Felizia Holzinger",
          "Louisa Kaufmann",
          "Fiona Kurz",
          "Sophie Lüdtke",
          "Mia Mai",
          "Lisa Maierhöfer",
          "Leonie Mayer",
          "Hanna Merz",
          "Hannah Rieger",
          "Leni Vatter",
          "Emma Weber",
          "Melina Ziegelbauer",
        ],
      },
    ],
  },
  {
    tabname: "Jugendgarde",
    defs: [
      {
        year: 2020,
        show: "Hände hoch! Polizei!",
        title: "Jugendgarde",
        leaders: ["Sandra Feil", "Vanessa Rupp"],
        active: [],
      },
      {
        year: 2019,
        show: "It's a me, Mario!",
        title: "Kindergarde",
        leaders: ["Sandra Feil"],
        active: [
          "Nina Abele",
          "Verena Fauser",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nele Jotz",
          "Nina Mack",
          "Nora Pautz",
          "Lotta Schuster",
          "Anna-Lena Sekler",
          "Emma Weiß",
        ],
      },
      {
        year: 2018,
        show: "Aloha!",
        title: "Kindergarde",
        leaders: ["Sandra Feil"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nele Jotz",
          "Nina Mack",
          "Nora Pautz",
          "Eva Brenner-Schmid",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Emma Weiß",
        ],
      },
      {
        year: 2017,
        show: "Hercules und seine Musen",
        title: "Kindergarde",
        leaders: ["Sandra Feil"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nele Jotz",
          "Jana Köder",
          "Nina Mack",
          "Nora Pautz",
          "Eva Schmid Brenner",
          "Lotta Schuster",
          "Anna-Lena Seckler",
        ],
      },
      {
        year: 2016,
        show: "Das große Krabbeln",
        title: "Kindergarde",
        leaders: ["Sandra Feil", "Lisa Maile"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nina Hauber",
          "Nele Jotz",
          "Jana Köder",
          "Nina Mack",
          "Nora Pautz",
          "Eva Schmid",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Layba Daud",
        ],
      },
      {
        year: 2015,
        show: "Tarzan und Jane",
        title: "Minigarde",
        leaders: ["Sandra Feil", "Lisa Maile", "Vera Maile"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nina Hauber",
          "Nele Jotz",
          "Jana Köder",
          "Nina Mack",
          "Nora Pautz",
          "Eva Schmid",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Anna-Lena Tolnai",
          "Simona Zekl",
          "Paula Kohnle",
          "Annika Dürrschmidt",
        ],
      },
      {
        year: 2014,
        show: "-",
        title: "Minigarde",
        leaders: ["Sandra Feil", "Lisa Maile", "Vera Maile"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Annika Dürrschmidt",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nina Hauber",
          "Nele Jotz",
          "Jana Köder",
          "Paula Kohnle",
          "Nina Mack",
          "Nora Pautz",
          "Eva Schmid",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Rebecca Spaag",
          "Anna-Lena Tolnai",
          "Simona Zekl",
        ],
      },
      {
        year: 2013,
        show: "-",
        title: "Minigarde",
        leaders: ["Sandra Feil", "Lisa Maile", "Vera Maile"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nina Hauber",
          "Viktoria Holzinger",
          "Nele Jotz",
          "Jana Köder",
          "Nina Mack",
          "Nora Pautz",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Mona Szabo",
          "Anna-Lena Tolnai",
          "Simona Zekl",
          "Paula Kohnle",
          "Rebecca Spaag",
          "Anika Dürrschmidt",
        ],
      },
      {
        year: 2012,
        show: "-",
        title: "Minigarde",
        leaders: ["Sandra Feil", "Lisa Maile", "Vera Maile"],
        active: [
          "Nina Abele",
          "Pauline Aschauer",
          "Verena Fauser",
          "Amelie Fischer",
          "Laura Fischer",
          "Casey Frei",
          "Selina Fürst",
          "Marlene Gerold",
          "Nina Hauber",
          "Viktoria Holzinger",
          "Nele Jotz",
          "Jana Köder",
          "Nina Mack",
          "Nora Pautz",
          "Samantha Rölke",
          "Lotta Schuster",
          "Anna-Lena Seckler",
          "Mona Szabo",
          "Anna-Lena Tolnai",
          "Simona Zekl",
        ],
      },
    ],
  },
  {
    tabname: "Prinzengarde",
    defs: [
      {
        year: 2020,
        show: "Das grauen der Nacht",
        title: "Prinzengarde",
        leaders: ["Ramona Vaas", "Vera Seidl"],
        active: [],
      },
      {
        year: 2019,
        show: "Ich will fliegen",
        title: "Jugendgarde",
        leaders: ["Ramona Vaas", "Vera Seidl"],
        active: [
          "Luisa Dirheimer",
          "Amelie Eiberger",
          "Lydia Frei",
          "Cora Gentner",
          "Denise Gentner",
          "Kathrin Gerold",
          "Evi Grundler",
          "Pauline Heinisch",
          "Julia Köder",
          "Laura Köhler",
          "Alina Liesch",
          "Leonie Mack",
          "Carolin Maile",
          "Julia Neumann",
          "Paula Schuster",
          "Constanze Stengel",
          "Pia Wanner",
        ],
      },
      {
        year: 2018,
        show: "Flossen hoch!",
        title: "Jugendgarde",
        leaders: ["Ramona Vaas", "Vera Seidl"],
        active: [
          "Luisa Dirheimer",
          "Amelie Eiberger",
          "Lydia Frei",
          "Cora Gentner",
          "Denise Gentner",
          "Kathrin Gerold",
          "Evi Grundler",
          "Pauline Heinisch",
          "Julia Köder",
          "Laura Köhler",
          "Alina Liesch",
          "Leonie Mack",
          "Carolin Maile",
          "Julia Neumann",
          "Paula Schuster",
          "Constanze Stengel ",
          "Pia Wanner",
        ],
      },
      {
        year: 2017,
        show: "Tatü Tata, die Feuerwehr ist da!",
        title: "Jugendgarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Luisa Dirheimer",
          "Amelie Eiberger",
          "Lydia Frei",
          "Cora Gentner",
          "Denise Gentner",
          "Kathrin Gerold",
          "Evi Grundler",
          "Pauline Heinisch",
          "Julia Köder",
          "Laura Köhler",
          "Alina Liesch",
          "Leonie Mack",
          "Carolin Maile",
          "Julia Neumann",
          "Paula Schuster",
          "Constanze Stengel",
          "Pia Wanner",
          "Jenny Wolf",
          "Luisa Zekl",
        ],
      },
      {
        year: 2016,
        show: "Hallelujah, heute wird geheiratet",
        title: "Jugendgarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Luisa Dirheimer",
          "Amelie Eiberger",
          "Lydia Frei",
          "Cora Gentner",
          "Denise Gentner",
          "Kathrin Gerold",
          "Evi Grundler",
          "Pauline Heinisch",
          "Annika Köder",
          "Nina Köder",
          "Julia Köder",
          "Laura Köhler",
          "Alina Liesch",
          "Leonie Mack",
          "Carolin Maile",
          "Julia Neumann",
          "Paula Schuster",
          "Constanze Stengel",
          "Pia Wanner",
          "Jenny Wolf",
          "Luisa Zekl",
        ],
      },
      {
        year: 2015,
        show: "Boy meets Girl",
        title: "Kindergarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Julia Köder",
          "Pia Wanner",
          "Cora Gentner",
          "Evi Grundler",
          "Nina Köder",
          "Kathrin Gerold",
          "Carolin Maile",
          "Jennifer Wolf",
          "Annika Köder",
          "Constanze Stengel",
          "Leonie Mack",
          "Pauline Heinisch",
          "Luisa Dirheimer",
          "Julia Neumann",
          "Alina Liesch",
          "Amelie Eiberger",
          "Denise Gentner",
          "Paula Schuster",
          "Hanna Hauber",
          "Luisa Zekl",
          "Laura Köhler",
        ],
      },
      {
        year: 2014,
        show: "Goldmarie und Pechmarie",
        title: "Kindergarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Julia Köder",
          "Pia Wanner",
          "Cora Gentner",
          "Loreen Eiberger",
          "Evi Grundler",
          "Nina Köder",
          "Kathrin Gerold",
          "Carolin Maile",
          "Jennifer Wolf",
          "Annika Köder",
          "Constanze Stengel",
          "Leonie Mack",
          "Pauline Heinisch",
          "Luisa Dirheimer",
          "Julia Neumann",
          "Alina Liesch",
          "Amelie Eiberger",
          "Denise Gentner",
          "Paula Schuster",
          "Hanna Hauber",
          "Luisa Zekl",
          "Laura Köhler",
        ],
      },
      {
        year: 2013,
        show: "Brennnesseln der Meere",
        title: "Kindergarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Julia Köder",
          "Corinna Christ",
          "Pia Wanner",
          "Cora Gentner",
          "Loreen Eiberger",
          "Evi Grundler",
          "Nina Köder",
          "Kathrin Gerold",
          "Carolin Maile",
          "Jennifer Wolf",
          "Annika Köder",
          "Constanze Stengel",
          "Leonie Mack",
          "Pauline Heinisch",
          "Luisa Dirheimer",
          "Julia Neumann",
          "Alina Liesch",
          "Amelie Eiberger",
          "Denise Gentner",
          "Paula Schuster",
          "Hanna Hauber",
          "Luisa Zekl",
          "Nicola Zekl ",
          "Emilia Zekl",
        ],
      },
      {
        year: 2012,
        show: "Ice Ice Pingui",
        title: "Kindergarde",
        leaders: ["Ramona Vaas", "Vera Schlotter"],
        active: [
          "Julia Köder",
          "Corinna Christ",
          "Pia Wanner",
          "Cora Gentner",
          "Loreen Eiberger",
          "Evi Grundler",
          "Nina Köder",
          "Kathrin Gerold",
          "Carolin Maile",
          "Jennifer Wolf",
          "Annika Köder",
          "Constanze Stengel",
          "Leonie Mack",
          "Pauline Heinisch",
          "Luisa Dirheimer",
          "Julia Neumann",
          "Alina Liesch",
          "Amelie Eiberger",
          "Denise Gentner",
          "Paula Schuster",
          "Hanna Hauber",
        ],
      },
      {
        year: 2011,
        show: "-",
        title: "Minigarde",
        leaders: ["Ramona Vaas", "Vera Schlotter", "Susanne Köder"],
        active: [
          "Julia Köder",
          "Corinna Christ",
          "Pia Wanner",
          "Cora Gentner",
          "Loreen Eiberger",
          "Evi Grundler",
          "Nina Köder",
          "Kathrin Gerold",
          "Carolin Maile",
          "Jenni Wolf",
          "Annika Köder",
          "Constanze Stengel",
          "Leonie Mack",
          "Pauline Heinisch",
          "Luisa Dirheimer",
          "Julia Neumann",
          "Alina Liesch",
          "Amelie Eiberger",
          "Denise Gentner",
          "Paula Schuster",
          "Hanna Hauber",
        ],
      },
      {
        year: 2010,
        show: "-",
        title: "Minigarde",
        leaders: ["Ramona Vaas", "Vera Schlotter", "Christl Rieger", "Susanne Köder"],
        active: [
          "Corinna Christ",
          "Luisa Dirheimer",
          "Amelie Eiberger",
          "Loreen Eiberger",
          "Cora Gentner",
          "Denise Gentner",
          "Kathrin Gerold",
          "Janine Gruber",
          "Evi Grundler",
          "Hanna Hauber",
          "Pauline Heinisch",
          "Annika Köder",
          "Nina Köder",
          "Julia Köder",
          "Alina Liesch",
          "Leonie Mack",
          "Carolin Maile",
          "Julia Neumann",
          "Luisa Scheuring",
          "Paula Schuster",
          "Constanze Stengel",
          "Pia Wanner",
          "Jennifer Wolf",
        ],
      },
      {
        year: 2010,
        show: "-",
        title: "Minigarde",
        leaders: ["Ramona Vaas", "Vera Schlotter", "Susanne Köder"],
        active: [
          "Corinna Christ",
          "Luisa Dirheimer",
          "Loreen Eiberger",
          "Cora Gentner",
          "Kathrin Gerold",
          "Evi Grundler",
          "Johanna Haas",
          "Hanna Hauber",
          "Pauline Heinisch",
          "Annika Köder",
          "Nina Köder",
          "Julia Köder",
          "Alina Liesch",
          "Leonie Mack",
          "Lisa Mack",
          "Carolin Maile",
          "Paula Schuster",
          "Nina Steiner",
          "Jana Steiner",
          "Constanze Stengel",
          "Charlotte Uhl",
          "Pia Wanner",
          "Jennifer Wolf",
          "Janine Gruber",
          "Amelie Eiberger",
          "Julia Neumann",
          "Luisa Scheuring",
        ],
      },
    ],
  },
  { tabname: "1. Garde", defs: [] },
];
