POST http://localhost/api/person/ HTTP/1.1
content-type: application/json

{
    "name": "John"
}

###

PUT http://localhost/api/person/John HTTP/1.1
Content-Type: application/json

{
    "name": "foo"
}

###

GET http://localhost/api/person/ HTTP/1.1

###

DELETE  http://localhost/api/person/John HTTP/1.1