version: '3.5'
services:
  middleware:
    tty: true
    build:
      context: ./middleware/
      dockerfile: $PWD/Docker/dev.middleware.Dockerfile
    volumes:
      - './middleware/:/app'
      - '/app/node_modules'
    links:
      - mongo
  angular:
    tty: true
    build:
      context: ./frontend/
      dockerfile: $PWD/Docker/dev.frontend.Dockerfile
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
  mongo:
    tty: true
    build:
      context: ./database/
      dockerfile: $PWD/Docker/database.Dockerfile
    ports:
      - 27017:27017
    volumes:
      - ./database/storage:/data/db
  nginx:
    tty: true
    build:
      context: ./proxy/
      dockerfile: $PWD/Docker/proxy.Dockerfile
    ports:
      - 5000:80
    links:
      - middleware
      - angular
