version: '3.5'

services:
  go:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    links:
      - mongo
  svelte:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/usr/src/app'
      # this anonymous volume prevents the node_modules from being overwritten
      - '/usr/src/app/node_modules'
    ports:
      - 35729:35729
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database/storage:/data/db
  nginx:
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      ports:
        - 5000:80
      links:
      - go
      - svelte
