version: '3.5'
services:
  mongo:
    tty: true
    image: mongo:latest
    volumes:
      - ./database:/data/db
  app:
    tty: true
    build:
      context: ./app
      dockerfile: prod.Dockerfile
    ports:
      - 80:3000
    links:
      - mongo
    depends_on:
      - mongo
