version: '3.5'
services:
  database:
    tty: true
    build:
      context: ./app/database
      dockerfile: $PWD/app/docker/database.Dockerfile

  middleware:
    tty: true
    environment:
      - NODE_ENV=production
      - TZ='Europe/Amsterdam'
    build:
      context: ./app/middleware
      dockerfile: $PWD/app/docker/middleware.Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - './app/middleware:/app'
    links:
      - database
