version: '3.3'
services:
  ngnix:
    build:
      context: .
      dockerfile: ./prod-env-hosting/Dockerfile
    ports:
      - '5500:8080'
    volumes:
      - ./prod-env-hosting/nginx.conf:/etc/nginx/nginx.conf
      - ../hosting/dist/roesena-app/:/data/www/
