name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  bump-version-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  deploy_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages for hosting
        working-directory: ./hosting
        run: npm ci

      - name: Install packages for functions
        working-directory: ./functions
        run: npm ci

      - name: Install firebase-tools globaly
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token $FIREBASE_TOKEN --project sechta-narren
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
