name: deploy app
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo and compose on server with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            [ -d "./roesena-app" ] && cd roesena-app && docker-compose down && cd ..
            sudo rm -f -R roesena-app
            git clone --single-branch --branch master https://github.com/jgero/roesena-app.git
            cd roesena-app
            docker-compose -f docker-compose.yml up --build -d
