name: Test

on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages
        working-directory: ./hosting
        run: npm ci

      - name: lint project
        working-directory: ./hosting
        run: npm run lint

      - name: run unit tests
        working-directory: ./hosting
        run: npm run test:ci
