name: unit tests
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: run test stack
        run: make unit-tests
